<?php

namespace AA\Front\TalksBundle\Repository;

use AA\Core\UserBundle\Entity\Brother;
use AA\Front\TalksBundle\Entity\Topic;
use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
    /**
     * @return \AA\Front\TalksBundle\Entity\Topic[]|ArrayCollection
     */
    public function getTopics(){
        $topics = $this->_em
            ->getRepository('AAFrontTalksBundle:Topic')
            ->findAll()
        ;

        return new ArrayCollection($topics);
    }

    /**
     * @param $topicId
     * @return \AA\Front\TalksBundle\Entity\Topic
     */
    public function getTopic($topicId){
        $topic = $this->_em
            ->getRepository('AAFrontTalksBundle:Topic')
            ->findOneBy(['id' => $topicId])
        ;

        return $topic;
    }

    /**
     * @param Brother $user
     * @param string $subject
     * @param string $content
     */
    public function createTopic(Brother $user, $subject = "", $content = "")
    {
        $topic = new Topic($user, $subject, $content);
        $this->_em->persist($topic);
        $this->_em->flush();

        return $topic;
    }
}
